version: '3.9'

services:
  redis:
    container_name: ToDoApp-redis
    image: redis
    restart: always
    ports:
    -  "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  web:
    build: . 
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app/
    ports:
      - "8000:8000"
    environment:
      - "SECRET_KEY=${DOCKER_COMPOSE_SECRET_KEY}"
      - "DEBUG=${DOCKER_COMPOSE_DEBUG}"
    depends_on:
      - redis
    
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - web
    
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  locust-worker:
    image: locustio/locust
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master